### ISSUE TITLE
gulp lambda:init doesn't work

### ISSUE THREAD

**Issue by Yishay** [stevejhiggs/aws-lambda-typescript#10]
Hi,

I followed the steps in the help and got:
```
...\node_modules\aws-lambda-typescript\localServer.js:6
  app.post('/', async (req, res) => {
                      ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\node_modules\aws-lambda-typescript\index.js:10:21)
```

Help will be appreciated.
Thanks,
Yishay

**Comment by Yishay** [comment]
seems to be a node version
https://github.com/fastify/benchmarks/issues/16

**Comment by Yishay** [comment]
worked with node 10
