### ISSUE TITLE
gulp lambda:run / package runtime error

### ISSUE THREAD

**Issue by omatrot** [stevejhiggs/aws-lambda-typescript#8]
I am not able to run either gulp lambda:run/package. It fails with the following error:

gulp lambda:package
>SyntaxError: Unexpected token ] in JSON at position 262
    at Object.parse (native)
    at parse (/Users/omatrot/Projects/code/lambda/node_modules/tsconfig/src/tsconfig.ts:195:15)
    at readFileSync (/Users/omatrot/Projects/code/lambda/node_modules/tsconfig/src/tsconfig.ts:181:10)
    at Object.loadSync (/Users/omatrot/Projects/code/lambda/node_modules/tsconfig/src/tsconfig.ts:151:18)
    at readConfig (/Users/omatrot/Projects/code/lambda/node_modules/ts-node/src/index.ts:425:18)
    at Object.register (/Users/omatrot/Projects/code/lambda/node_modules/ts-node/src/index.ts:189:18)
    at Object.<anonymous> (/Users/omatrot/Projects/code/lambda/node_modules/aws-lambda-typescript/localServer.js:1:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

can't figure out what JSON this is about.

**Comment by stevejhiggs** [comment]
It looks like an error parsing out your tsconfig.json, could you post the contents here?

**Comment by omatrot** [comment]
`{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "lib": [
      "es2015",
    ],
    "outDir": "out"
  },
  "exclude": [
    "dist",
    "node_modules"
  ],
}`

**Comment by omatrot** [comment]
You were right, the problem was:
>"lib": [ "es2015", ]

With:
>"lib": [ "es2015"]

It is OK.

**Comment by stevejhiggs** [comment]
yay!
